version: "2"
services:
    adminer:
        image: "adminer:standalone"
        ports: 
            - "8080:8080"
        links:
            - db
    db:
        image: "mysql:latest"
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - ./db:/tmp/db

    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - .:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php

    php:
        build: docker_env
        volumes:
            - .:/code
        links:
            - db
